/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.gui.core;

import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import main.structures.Product;

/**
 *
 * @author Matt HP
 */
public class NewProductDialog extends javax.swing.JDialog
{
    Product product = new Product();
    ResultSet results;

    /**
     * Creates new form NewJDialog
     */
    public NewProductDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        product = new Product();
       // results = in_results;
        for(String record : product.size_array)
        {
            size_combo_box.addItem(record);
        }
        
        for(String record : product.category_array)
        {
            category_combo_box.addItem(record);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description_area = new javax.swing.JTextArea();
        price = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        product_id = new javax.swing.JTextField();
        product_name = new javax.swing.JTextField();
        category_combo_box = new javax.swing.JComboBox<>();
        size_combo_box = new javax.swing.JComboBox<>();
        cancel_button = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Product Id:");

        jLabel2.setText("Product Name:");

        jLabel3.setText("Category:");

        jLabel4.setText("Size:");

        jLabel5.setText("Quantity");

        jLabel6.setText("Price:");

        jLabel7.setText("Description:");

        description_area.setColumns(20);
        description_area.setRows(5);
        jScrollPane1.setViewportView(description_area);

        price.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                priceActionPerformed(evt);
            }
        });

        quantity.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quantityActionPerformed(evt);
            }
        });

        size_combo_box.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                size_combo_boxActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancel_buttonActionPerformed(evt);
            }
        });

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(price)
                            .addComponent(quantity)
                            .addComponent(product_id)
                            .addComponent(product_name)
                            .addComponent(category_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(size_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(cancel_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addItemButton)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(product_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(category_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(size_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button)
                    .addComponent(addItemButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancel_buttonActionPerformed
    {//GEN-HEADEREND:event_cancel_buttonActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void size_combo_boxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_size_combo_boxActionPerformed
    {//GEN-HEADEREND:event_size_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size_combo_boxActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addItemButtonActionPerformed
    {//GEN-HEADEREND:event_addItemButtonActionPerformed
        if (formLegalities() && resultsLegalies())
        {       
          product.setPrice(Double.parseDouble(price.getText()));
          product.setQuantity(Integer.parseInt(quantity.getText()));
          product.setProductId(product_id.getText());
          product.setProductName(product_name.getText());
          product.setDescription(description_area.getText());
          product.setCategory(category_combo_box.getSelectedItem().toString());
          product.setCategory(size_combo_box.getSelectedItem().toString());
          this.setVisible(false);
        }
       
    }//GEN-LAST:event_addItemButtonActionPerformed

    public Product getNewProduct()
    {
       return product;
    }
    private boolean resultsLegalies()
    {
        boolean valid = true;
        
        return valid;
    }
    private boolean formLegalities()
    {
        boolean valid = true;
        String error_msg = "";
        try {
          Double.parseDouble(price.getText());
       }
       catch (NumberFormatException e) {     
           error_msg = "ENTER A VALID PRICE";
           valid = false;
       }
       try {
           Integer.parseInt(quantity.getText());
       }
       catch (NumberFormatException e) {  
           error_msg = "ENTER A VALID QUANTITY";
           valid = false;
       }
       if(0 == product_id.getText().length())
       {
          error_msg = "ENTER A VALID PRODUCT ID";
          valid = false;
       }
       else if(0 == product_name.getText().length())
       {
          error_msg = "ENTER A VALID PRODUCT NAME";
          valid = false;
       }
       else if(0 == description_area.getText().length())
       {
          error_msg = "ENTER A DESCRIPTION";
          valid = false;
       }
       
       if (!valid)
       {
           JOptionPane optionPane = new JOptionPane(error_msg, JOptionPane.ERROR_MESSAGE);    
           JDialog dialog = optionPane.createDialog("Failure");
           dialog.setAlwaysOnTop(true);
           dialog.setVisible(true);
       }
       return valid;
    }
    
    private void priceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_priceActionPerformed
    {//GEN-HEADEREND:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quantityActionPerformed
    {//GEN-HEADEREND:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton cancel_button;
    private javax.swing.JComboBox<String> category_combo_box;
    private javax.swing.JTextArea description_area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField price;
    private javax.swing.JTextField product_id;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField quantity;
    private javax.swing.JComboBox<String> size_combo_box;
    // End of variables declaration//GEN-END:variables
}
