/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.gui.core;

import java.awt.CardLayout;
import java.util.Date;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.*;
import main.implementation.InventoryImpl;
import main.interfaces.InventoryInterface_I;
import main.implementation.TransactionImpl;
import main.interfaces.TransactionInterface_I;
import main.structures.Transaction;
import main.structures.Product;

/**
 *
 * @author Dakota
 */
public class TransactionsPanel extends javax.swing.JPanel {

    InventoryInterface_I in_inventory_accessor = new InventoryImpl();
    
    private double subtotal;
    private double tax;
    private double total;
    private boolean delete;
    JFrame item_popup;
    
    private double trans_tax;
    private double trans_total;
    private String trans_date;
    private String trans_id;
    private String trans_payment;
    
    
    /**
     * Creates new form TransactionsPanel
     */
    
    public TransactionsPanel() {
        initComponents();
        removeitem_button.setVisible(false);
        subtotal = 00.00;
        tax = 00.00;
        total = 00.00;
        delete=false;
        
        //Listener to grab item information and display it on the sidebar
        ListSelectionModel jt = transaction_table.getSelectionModel();
        jt.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                if (!delete) {
                    product_id_textfield.setText(transaction_table.getValueAt(transaction_table.getSelectedRow(), 0).toString());
                    String item_code_display = transaction_table.getValueAt(transaction_table.getSelectedRow(), 0).toString();
                    Product record_display =in_inventory_accessor.getProduct(item_code_display);
                    if(record_display.getProductId().equals(item_code_display))
                        {
                            product_id_textfield.setText(record_display.getProductId());
                            category_jtextfield.setText(record_display.getCategory());
                            product_name_textfield.setText(record_display.getProductName());
                            description_jtextarea.setText(record_display.getDescription());
                            size_jtextfield.setText(record_display.getSize());
                            price_jtextfield.setText(String.valueOf(record_display.getPrice()));
                            quantity_jtextfield.setText(String.valueOf(record_display.getQuantity()));
                        }
                    
                    removeitem_button.setVisible(true);
                }
                else{
                    
                    product_id_textfield.setText("");
                    category_jtextfield.setText("");
                    product_name_textfield.setText("");
                    description_jtextarea.setText("");
                    size_jtextfield.setText("");
                    price_jtextfield.setText("");
                    quantity_jtextfield.setText("");
                    removeitem_button.setVisible(false);
                }
            }
        });
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_jpanel = new javax.swing.JPanel();
        company_name_label = new javax.swing.JLabel();
        product_table_jpanel = new javax.swing.JPanel();
        button_panel1 = new javax.swing.JPanel();
        enter_code_button = new javax.swing.JButton();
        enter_coupon_button = new javax.swing.JButton();
        finalze_button = new javax.swing.JButton();
        empty_cart_button = new javax.swing.JButton();
        button_panel2 = new javax.swing.JPanel();
        subtotal_label = new javax.swing.JLabel();
        taxes_label = new javax.swing.JLabel();
        coupons_label = new javax.swing.JLabel();
        total_label = new javax.swing.JLabel();
        subtotal_variable = new javax.swing.JLabel();
        coupons_variable = new javax.swing.JLabel();
        taxes_variable = new javax.swing.JLabel();
        total_variable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaction_table = new javax.swing.JTable();
        product_jpanel = new javax.swing.JPanel();
        icon_jpanel = new javax.swing.JPanel();
        icon_jLabel = new javax.swing.JLabel();
        product_jlabel = new javax.swing.JLabel();
        product_name_jbutton = new javax.swing.JLabel();
        product_id_textfield = new javax.swing.JTextField();
        product_name_textfield = new javax.swing.JTextField();
        quantity_jlabel = new javax.swing.JLabel();
        quantity_jtextfield = new javax.swing.JTextField();
        price_jlabel = new javax.swing.JLabel();
        price_jtextfield = new javax.swing.JTextField();
        category_jlabel = new javax.swing.JLabel();
        category_jtextfield = new javax.swing.JTextField();
        description_jlabel = new javax.swing.JLabel();
        description_jscrollpane = new javax.swing.JScrollPane();
        description_jtextarea = new javax.swing.JTextArea();
        size_label = new javax.swing.JLabel();
        size_jtextfield = new javax.swing.JTextField();
        button_panel = new javax.swing.JPanel();
        inventory_button = new javax.swing.JButton();
        admin_jbutton = new javax.swing.JButton();
        menu_jbutton = new javax.swing.JButton();
        removeitem_button = new javax.swing.JButton();
        loco_icon_panel = new javax.swing.JPanel();
        logo_jlabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1878, 1038));

        logo_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        company_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        company_name_label.setText("COMPANY NAME");

        javax.swing.GroupLayout logo_jpanelLayout = new javax.swing.GroupLayout(logo_jpanel);
        logo_jpanel.setLayout(logo_jpanelLayout);
        logo_jpanelLayout.setHorizontalGroup(
            logo_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(company_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logo_jpanelLayout.setVerticalGroup(
            logo_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo_jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(company_name_label)
                .addContainerGap())
        );

        product_table_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        button_panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        enter_code_button.setText("Enter Code");
        enter_code_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_code_buttonActionPerformed(evt);
            }
        });

        enter_coupon_button.setBackground(new java.awt.Color(255, 0, 0));
        enter_coupon_button.setText("Enter Coupon");
        enter_coupon_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_coupon_buttonActionPerformed(evt);
            }
        });

        finalze_button.setText("Finalize");
        finalze_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalze_buttonActionPerformed(evt);
            }
        });

        empty_cart_button.setText("Empty Cart");
        empty_cart_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empty_cart_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_panel1Layout = new javax.swing.GroupLayout(button_panel1);
        button_panel1.setLayout(button_panel1Layout);
        button_panel1Layout.setHorizontalGroup(
            button_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enter_coupon_button, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enter_code_button, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(empty_cart_button, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(finalze_button, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        button_panel1Layout.setVerticalGroup(
            button_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enter_coupon_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finalze_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enter_code_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empty_cart_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        button_panel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        subtotal_label.setText("Subtotal:");

        taxes_label.setText("Taxes:");

        coupons_label.setText("Coupons:");

        total_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total_label.setText("Total:");

        subtotal_variable.setText("$00.00");

        coupons_variable.setText("$00.00");

        taxes_variable.setText("$00.00");

        total_variable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total_variable.setText("$00.00");

        javax.swing.GroupLayout button_panel2Layout = new javax.swing.GroupLayout(button_panel2);
        button_panel2.setLayout(button_panel2Layout);
        button_panel2Layout.setHorizontalGroup(
            button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total_label)
                    .addComponent(coupons_label)
                    .addComponent(taxes_label)
                    .addComponent(subtotal_label))
                .addGap(66, 66, 66)
                .addGroup(button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(subtotal_variable)
                        .addComponent(coupons_variable)
                        .addComponent(taxes_variable))
                    .addComponent(total_variable))
                .addGap(30, 30, 30))
        );
        button_panel2Layout.setVerticalGroup(
            button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotal_label)
                    .addComponent(subtotal_variable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxes_label)
                    .addComponent(taxes_variable))
                .addGap(18, 18, 18)
                .addGroup(button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coupons_label)
                    .addComponent(coupons_variable))
                .addGap(18, 18, 18)
                .addGroup(button_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_label)
                    .addComponent(total_variable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transaction_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Type", "Price", ""
            }
        ));
        jScrollPane1.setViewportView(transaction_table);

        javax.swing.GroupLayout product_table_jpanelLayout = new javax.swing.GroupLayout(product_table_jpanel);
        product_table_jpanel.setLayout(product_table_jpanelLayout);
        product_table_jpanelLayout.setHorizontalGroup(
            product_table_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_table_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product_table_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(product_table_jpanelLayout.createSequentialGroup()
                        .addComponent(button_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product_table_jpanelLayout.setVerticalGroup(
            product_table_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, product_table_jpanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(product_table_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        product_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        icon_jpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        icon_jLabel.setText("ICON");

        javax.swing.GroupLayout icon_jpanelLayout = new javax.swing.GroupLayout(icon_jpanel);
        icon_jpanel.setLayout(icon_jpanelLayout);
        icon_jpanelLayout.setHorizontalGroup(
            icon_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, icon_jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_jLabel)
                .addGap(32, 32, 32))
        );
        icon_jpanelLayout.setVerticalGroup(
            icon_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_jpanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(icon_jLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product_jlabel.setText("Product ID:");

        product_name_jbutton.setText("Product Name: ");

        product_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_name_textfieldActionPerformed(evt);
            }
        });

        quantity_jlabel.setText("Qty :");

        quantity_jtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_jtextfieldActionPerformed(evt);
            }
        });

        price_jlabel.setText("Price :");

        price_jtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_jtextfieldActionPerformed(evt);
            }
        });

        category_jlabel.setText("Category :");

        category_jtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_jtextfieldActionPerformed(evt);
            }
        });

        description_jlabel.setText("Description :");

        description_jtextarea.setColumns(20);
        description_jtextarea.setRows(5);
        description_jscrollpane.setViewportView(description_jtextarea);

        size_label.setText("Size :");

        button_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inventory_button.setText("Inventory");
        inventory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventory_buttonActionPerformed(evt);
            }
        });

        admin_jbutton.setText("Admin");

        menu_jbutton.setText("Menu");
        menu_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_panelLayout = new javax.swing.GroupLayout(button_panel);
        button_panel.setLayout(button_panelLayout);
        button_panelLayout.setHorizontalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inventory_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu_jbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(admin_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        button_panelLayout.setVerticalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admin_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(menu_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        removeitem_button.setBackground(new java.awt.Color(255, 0, 0));
        removeitem_button.setText("Remove Item");
        removeitem_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitem_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product_jpanelLayout = new javax.swing.GroupLayout(product_jpanel);
        product_jpanel.setLayout(product_jpanelLayout);
        product_jpanelLayout.setHorizontalGroup(
            product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_jpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(category_jlabel)
                    .addComponent(quantity_jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(product_jpanelLayout.createSequentialGroup()
                        .addComponent(category_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(size_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(size_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(product_jpanelLayout.createSequentialGroup()
                        .addComponent(quantity_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(price_jlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(product_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(product_jpanelLayout.createSequentialGroup()
                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(product_jpanelLayout.createSequentialGroup()
                        .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(product_name_jbutton)
                            .addComponent(product_jlabel))
                        .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(product_jpanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(icon_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(product_jpanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(product_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(product_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(product_jpanelLayout.createSequentialGroup()
                        .addComponent(description_jlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeitem_button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(description_jscrollpane))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product_jpanelLayout.setVerticalGroup(
            product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_jpanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_name_jbutton))
                .addGap(18, 18, 18)
                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category_jlabel)
                    .addComponent(category_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size_label)
                    .addComponent(size_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(price_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantity_jlabel)
                        .addComponent(quantity_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(price_jlabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(product_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description_jlabel)
                    .addComponent(description_jscrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(removeitem_button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        loco_icon_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logo_jlabel.setText("LOGO");

        javax.swing.GroupLayout loco_icon_panelLayout = new javax.swing.GroupLayout(loco_icon_panel);
        loco_icon_panel.setLayout(loco_icon_panelLayout);
        loco_icon_panelLayout.setHorizontalGroup(
            loco_icon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loco_icon_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo_jlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loco_icon_panelLayout.setVerticalGroup(
            loco_icon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loco_icon_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logo_jlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loco_icon_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(logo_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(product_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(product_table_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loco_icon_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(product_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(product_table_jpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inventory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventory_buttonActionPerformed
        CardLayout card = (CardLayout)this.getParent().getLayout();
        card.show(this.getParent(), "inventoryManagementPanel");
    }//GEN-LAST:event_inventory_buttonActionPerformed

    private void menu_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jbuttonActionPerformed
        CardLayout card = (CardLayout)this.getParent().getLayout();
        card.show(this.getParent(), "launcherMenuPanel");
    }//GEN-LAST:event_menu_jbuttonActionPerformed

    private void enter_code_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_code_buttonActionPerformed
   
        String item_code = JOptionPane.showInputDialog(item_popup, "Enter Item Code",null);
        
        if (item_code != null) {
            DefaultTableModel model = (DefaultTableModel) transaction_table.getModel();
            Product record =in_inventory_accessor.getProduct(item_code);
            
           if(record.getProductId().equals(item_code))
           {
                Object[] row =
                {
                    item_code,
                    record.getProductName(),
                    record.getCategory(),
                    record.getPrice(),
                    "DELETE"
                };

                model.addRow(row);
                DecimalFormat df = new DecimalFormat("0.00");

                subtotal=subtotal+record.getPrice();
                tax=tax+(record.getPrice()*0.07);
                total=total+(record.getPrice()*1.07);

                subtotal_variable.setText("$"+df.format(subtotal));
                taxes_variable.setText("$"+df.format(tax));
                total_variable.setText("$"+df.format(total));
            }
           else {
               JOptionPane.showMessageDialog(item_popup,"INCORRECT ITEM CODE ENTERED","ERROR",JOptionPane.ERROR_MESSAGE);
           }
        }

    }//GEN-LAST:event_enter_code_buttonActionPerformed

    private void enter_coupon_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_coupon_buttonActionPerformed
        
    }//GEN-LAST:event_enter_coupon_buttonActionPerformed

    private void product_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_name_textfieldActionPerformed
       
    }//GEN-LAST:event_product_name_textfieldActionPerformed

    private void quantity_jtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_jtextfieldActionPerformed
      
    }//GEN-LAST:event_quantity_jtextfieldActionPerformed

    private void price_jtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_jtextfieldActionPerformed
 
    }//GEN-LAST:event_price_jtextfieldActionPerformed

    private void category_jtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_jtextfieldActionPerformed
     
    }//GEN-LAST:event_category_jtextfieldActionPerformed

    private void empty_cart_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empty_cart_buttonActionPerformed
        delete=true;
        DefaultTableModel model = (DefaultTableModel) transaction_table.getModel();
        model.setRowCount(0);
        subtotal=0;
        tax=0;
        total=0;
        subtotal_variable.setText("$00.00");
        taxes_variable.setText("$00.00");
        total_variable.setText("$00.00");
        delete=false;
    }//GEN-LAST:event_empty_cart_buttonActionPerformed

    private void removeitem_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitem_buttonActionPerformed
        delete=true;
        DefaultTableModel model = (DefaultTableModel) transaction_table.getModel();
        int SelectedRowIndex = transaction_table.getSelectedRow();
        model.removeRow(SelectedRowIndex);
        delete=false;
    }//GEN-LAST:event_removeitem_buttonActionPerformed

    private void finalze_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalze_buttonActionPerformed
        trans_tax=tax;
        trans_total=total;
        trans_date = new SimpleDateFormat("dd-MM-yyyy").format(new Date());
        trans_id="00001";
        trans_payment="CASH";
             
        Transaction trans = new Transaction();
        trans.setTransID(trans_id);
        trans.setDate(trans_date);
        trans.setTotal(trans_total);
        trans.setTax(trans_tax);
        trans.setPayment(trans_payment);
        
        TransactionInterface_I in_transaction_accessor = new TransactionImpl();
        
        in_transaction_accessor.addTransaction(trans);     
        
        System.out.println(trans.getTransID());
        System.out.println(trans.getDate());
        System.out.println(trans.getTotal());
        System.out.println(trans.getTax());
        System.out.println(trans.getPayment());
        
        delete=true;
        DefaultTableModel model = (DefaultTableModel) transaction_table.getModel();
        model.setRowCount(0);
        subtotal=0;
        tax=0;
        total=0;
        subtotal_variable.setText("$00.00");
        taxes_variable.setText("$00.00");
        total_variable.setText("$00.00");
        delete=false;
    }//GEN-LAST:event_finalze_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_jbutton;
    private javax.swing.JPanel button_panel;
    private javax.swing.JPanel button_panel1;
    private javax.swing.JPanel button_panel2;
    private javax.swing.JLabel category_jlabel;
    private javax.swing.JTextField category_jtextfield;
    private javax.swing.JLabel company_name_label;
    private javax.swing.JLabel coupons_label;
    private javax.swing.JLabel coupons_variable;
    private javax.swing.JLabel description_jlabel;
    private javax.swing.JScrollPane description_jscrollpane;
    private javax.swing.JTextArea description_jtextarea;
    private javax.swing.JButton empty_cart_button;
    private javax.swing.JButton enter_code_button;
    private javax.swing.JButton enter_coupon_button;
    private javax.swing.JButton finalze_button;
    private javax.swing.JLabel icon_jLabel;
    private javax.swing.JPanel icon_jpanel;
    private javax.swing.JButton inventory_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loco_icon_panel;
    private javax.swing.JLabel logo_jlabel;
    private javax.swing.JPanel logo_jpanel;
    private javax.swing.JButton menu_jbutton;
    private javax.swing.JLabel price_jlabel;
    private javax.swing.JTextField price_jtextfield;
    private javax.swing.JTextField product_id_textfield;
    private javax.swing.JLabel product_jlabel;
    private javax.swing.JPanel product_jpanel;
    private javax.swing.JLabel product_name_jbutton;
    private javax.swing.JTextField product_name_textfield;
    private javax.swing.JPanel product_table_jpanel;
    private javax.swing.JLabel quantity_jlabel;
    private javax.swing.JTextField quantity_jtextfield;
    private javax.swing.JButton removeitem_button;
    private javax.swing.JTextField size_jtextfield;
    private javax.swing.JLabel size_label;
    private javax.swing.JLabel subtotal_label;
    private javax.swing.JLabel subtotal_variable;
    private javax.swing.JLabel taxes_label;
    private javax.swing.JLabel taxes_variable;
    private javax.swing.JLabel total_label;
    private javax.swing.JLabel total_variable;
    private javax.swing.JTable transaction_table;
    // End of variables declaration//GEN-END:variables
}
