/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.gui.core;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.structures.Employee;
import main.interfaces.Employee_I;

/**
 *
 * @author Dakota
 */
public class UserManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserManagementPanel
     */
    public UserManagementPanel(Employee_I employee_handler) {
        initComponents();
        this.EMPLOYEE_ID_COLUMN = 0;
        this.EMPLOYEE_FIRST_NAME_COLUMN = 1;
        this.EMPLOYEE_LAST_NAME_COLUMN = 2;
        this.EMPLOYEE_ADDRESS_COLUMN = 3;
        this.EMPLOYEE_WAGE_COLUMN = 4;
        this.EMPLOYEE_HOURS_COLUMN = 5;
        this.employee_handler = employee_handler;
        showAllEmployees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_radio_button_group = new javax.swing.ButtonGroup();
        logo_jpanel = new javax.swing.JPanel();
        loco_icon_panel = new javax.swing.JPanel();
        logo_jlabel = new javax.swing.JLabel();
        company_name_label = new javax.swing.JLabel();
        option_jtabbedpane = new javax.swing.JTabbedPane();
        user_jpanel = new javax.swing.JPanel();
        icon_jpanel = new javax.swing.JPanel();
        icon_jLabel = new javax.swing.JLabel();
        employee_id_jlabel = new javax.swing.JLabel();
        first_name_jlabel = new javax.swing.JLabel();
        employee_id_textfield = new javax.swing.JTextField();
        first_name_textfield = new javax.swing.JTextField();
        address_jlabel = new javax.swing.JLabel();
        address_textfield = new javax.swing.JTextField();
        ssn_jlabel = new javax.swing.JLabel();
        ssn_textfield = new javax.swing.JTextField();
        wage_jlabel = new javax.swing.JLabel();
        wage_textfield = new javax.swing.JTextField();
        last_name_jlabel = new javax.swing.JLabel();
        last_name_textfield = new javax.swing.JTextField();
        hours_jlabel = new javax.swing.JLabel();
        hours_textfield = new javax.swing.JTextField();
        password_jlabel = new javax.swing.JLabel();
        password_textfield = new javax.swing.JPasswordField();
        admin_checkbox = new javax.swing.JCheckBox();
        user_dynamic_button_panel = new javax.swing.JPanel();
        user_standard_buttons = new javax.swing.JPanel();
        add_user_jbutton = new javax.swing.JButton();
        modify_user_jbutton = new javax.swing.JButton();
        delete_user_jbutton = new javax.swing.JButton();
        user_add_buttons = new javax.swing.JPanel();
        submit_add_user_button = new javax.swing.JButton();
        cancel_add_user_button = new javax.swing.JButton();
        user_modify_buttons = new javax.swing.JPanel();
        submit_modify_user_button = new javax.swing.JButton();
        cancel_modify_user_button = new javax.swing.JButton();
        search_jpanel = new javax.swing.JPanel();
        first_name_jradiobutton = new javax.swing.JRadioButton();
        last_name_jradiobutton = new javax.swing.JRadioButton();
        employee_id_jradiobutton = new javax.swing.JRadioButton();
        search_first_name_jtextfield = new javax.swing.JTextField();
        search_last_name_jtextfield = new javax.swing.JTextField();
        search_employee_id_jtextfield = new javax.swing.JTextField();
        search_jbutton = new javax.swing.JButton();
        button_panel = new javax.swing.JPanel();
        menu_jbutton = new javax.swing.JButton();
        user_table_jpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        user_jtable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1878, 1038));

        logo_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        loco_icon_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logo_jlabel.setText("LOGO");

        javax.swing.GroupLayout loco_icon_panelLayout = new javax.swing.GroupLayout(loco_icon_panel);
        loco_icon_panel.setLayout(loco_icon_panelLayout);
        loco_icon_panelLayout.setHorizontalGroup(
            loco_icon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loco_icon_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo_jlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loco_icon_panelLayout.setVerticalGroup(
            loco_icon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loco_icon_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logo_jlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        company_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        company_name_label.setText("COMPANY NAME");

        javax.swing.GroupLayout logo_jpanelLayout = new javax.swing.GroupLayout(logo_jpanel);
        logo_jpanel.setLayout(logo_jpanelLayout);
        logo_jpanelLayout.setHorizontalGroup(
            logo_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_jpanelLayout.createSequentialGroup()
                .addComponent(loco_icon_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logo_jpanelLayout.setVerticalGroup(
            logo_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo_jpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loco_icon_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(logo_jpanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(company_name_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        user_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        icon_jpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        icon_jLabel.setText("ICON");

        javax.swing.GroupLayout icon_jpanelLayout = new javax.swing.GroupLayout(icon_jpanel);
        icon_jpanel.setLayout(icon_jpanelLayout);
        icon_jpanelLayout.setHorizontalGroup(
            icon_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, icon_jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_jLabel)
                .addGap(32, 32, 32))
        );
        icon_jpanelLayout.setVerticalGroup(
            icon_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_jpanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(icon_jLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employee_id_jlabel.setText("Employee ID :");

        first_name_jlabel.setText("First Name : ");

        employee_id_textfield.setEditable(false);

        first_name_textfield.setEditable(false);

        address_jlabel.setText("Address :");

        address_textfield.setEditable(false);

        ssn_jlabel.setText("SSN :");

        ssn_textfield.setEditable(false);

        wage_jlabel.setText("Wage :");

        wage_textfield.setEditable(false);

        last_name_jlabel.setText("Last Name :");

        last_name_textfield.setEditable(false);

        hours_jlabel.setText("Hours :");

        hours_textfield.setEditable(false);

        password_jlabel.setText("Password");

        password_textfield.setEditable(false);

        admin_checkbox.setText("Administrator");
        admin_checkbox.setEnabled(false);

        user_dynamic_button_panel.setBackground(new java.awt.Color(255, 0, 255));
        user_dynamic_button_panel.setLayout(new java.awt.CardLayout());

        add_user_jbutton.setText("Add User");
        add_user_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_jbuttonActionPerformed(evt);
            }
        });

        modify_user_jbutton.setText("Modify User");
        modify_user_jbutton.setEnabled(false);
        modify_user_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_user_jbuttonActionPerformed(evt);
            }
        });

        delete_user_jbutton.setText("Delete User");
        delete_user_jbutton.setEnabled(false);
        delete_user_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_user_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout user_standard_buttonsLayout = new javax.swing.GroupLayout(user_standard_buttons);
        user_standard_buttons.setLayout(user_standard_buttonsLayout);
        user_standard_buttonsLayout.setHorizontalGroup(
            user_standard_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_standard_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modify_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_user_jbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        user_standard_buttonsLayout.setVerticalGroup(
            user_standard_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_standard_buttonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(user_standard_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        user_dynamic_button_panel.add(user_standard_buttons, "userStandardButtonsPanel");

        submit_add_user_button.setText("Submit");
        submit_add_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_add_user_buttonActionPerformed(evt);
            }
        });

        cancel_add_user_button.setText("Cancel");
        cancel_add_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_add_user_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout user_add_buttonsLayout = new javax.swing.GroupLayout(user_add_buttons);
        user_add_buttons.setLayout(user_add_buttonsLayout);
        user_add_buttonsLayout.setHorizontalGroup(
            user_add_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_add_buttonsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(submit_add_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(cancel_add_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        user_add_buttonsLayout.setVerticalGroup(
            user_add_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_add_buttonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(user_add_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_add_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_add_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        user_dynamic_button_panel.add(user_add_buttons, "userAddButtonsPanel");

        submit_modify_user_button.setText("Submit");
        submit_modify_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_modify_user_buttonActionPerformed(evt);
            }
        });

        cancel_modify_user_button.setText("Cancel");
        cancel_modify_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_modify_user_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout user_modify_buttonsLayout = new javax.swing.GroupLayout(user_modify_buttons);
        user_modify_buttons.setLayout(user_modify_buttonsLayout);
        user_modify_buttonsLayout.setHorizontalGroup(
            user_modify_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_modify_buttonsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(submit_modify_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(cancel_modify_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        user_modify_buttonsLayout.setVerticalGroup(
            user_modify_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_modify_buttonsLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(user_modify_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_modify_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_modify_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        user_dynamic_button_panel.add(user_modify_buttons, "userModifyButtonsPanel");

        javax.swing.GroupLayout user_jpanelLayout = new javax.swing.GroupLayout(user_jpanel);
        user_jpanel.setLayout(user_jpanelLayout);
        user_jpanelLayout.setHorizontalGroup(
            user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address_jlabel)
                    .addComponent(last_name_jlabel)
                    .addComponent(ssn_jlabel)
                    .addComponent(wage_jlabel)
                    .addComponent(hours_jlabel)
                    .addComponent(password_jlabel)
                    .addComponent(first_name_jlabel)
                    .addComponent(employee_id_jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(last_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssn_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wage_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_jpanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(icon_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(user_jpanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(admin_checkbox)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(user_dynamic_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        user_jpanelLayout.setVerticalGroup(
            user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_jpanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee_id_jlabel)
                    .addComponent(employee_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name_jlabel))
                .addGap(18, 18, 18)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_name_jlabel)
                    .addComponent(last_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_jlabel))
                .addGap(15, 15, 15)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssn_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssn_jlabel))
                .addGap(18, 18, 18)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wage_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wage_jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hours_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours_jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_jlabel)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(admin_checkbox)
                .addGap(32, 32, 32)
                .addComponent(user_dynamic_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        option_jtabbedpane.addTab("User", null, user_jpanel, "");

        search_radio_button_group.add(first_name_jradiobutton);
        first_name_jradiobutton.setSelected(true);
        first_name_jradiobutton.setText("First Name :");

        search_radio_button_group.add(last_name_jradiobutton);
        last_name_jradiobutton.setText("Last Name :");

        search_radio_button_group.add(employee_id_jradiobutton);
        employee_id_jradiobutton.setText("Employee ID :");

        search_jbutton.setText("Search");
        search_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_jpanelLayout = new javax.swing.GroupLayout(search_jpanel);
        search_jpanel.setLayout(search_jpanelLayout);
        search_jpanelLayout.setHorizontalGroup(
            search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_jpanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(last_name_jradiobutton)
                    .addComponent(employee_id_jradiobutton)
                    .addComponent(first_name_jradiobutton))
                .addGap(54, 54, 54)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_first_name_jtextfield)
                    .addComponent(search_last_name_jtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(search_employee_id_jtextfield))
                .addGap(74, 74, 74))
            .addGroup(search_jpanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(search_jbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        search_jpanelLayout.setVerticalGroup(
            search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_jpanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name_jradiobutton)
                    .addComponent(search_first_name_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_name_jradiobutton)
                    .addComponent(search_last_name_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_employee_id_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee_id_jradiobutton))
                .addGap(39, 39, 39)
                .addComponent(search_jbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        option_jtabbedpane.addTab("Search", null, search_jpanel, "");

        button_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menu_jbutton.setText("Menu");
        menu_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_panelLayout = new javax.swing.GroupLayout(button_panel);
        button_panel.setLayout(button_panelLayout);
        button_panelLayout.setHorizontalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(menu_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_panelLayout.setVerticalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        user_table_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        user_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Id", "First Name", "Last Name", "Address", "Wage", "Hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        user_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_jtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(user_jtable);

        javax.swing.GroupLayout user_table_jpanelLayout = new javax.swing.GroupLayout(user_table_jpanel);
        user_table_jpanel.setLayout(user_table_jpanelLayout);
        user_table_jpanelLayout.setHorizontalGroup(
            user_table_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_table_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1450, Short.MAX_VALUE)
                .addContainerGap())
        );
        user_table_jpanelLayout.setVerticalGroup(
            user_table_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_table_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(option_jtabbedpane)
                    .addComponent(button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_table_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(option_jtabbedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(user_table_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_user_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_jbuttonActionPerformed
        clearUserFormData();
        enableUserFormData();
        //Employee ID can only be edited on adding a user, not modifying
        employee_id_textfield.setEditable(true);

        
        //Change the buttons to the new options for adding a user
        CardLayout card = (CardLayout)user_dynamic_button_panel.getLayout();
        card.show(user_dynamic_button_panel, "userAddButtonsPanel");
    }//GEN-LAST:event_add_user_jbuttonActionPerformed

    private void delete_user_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_user_jbuttonActionPerformed
        int dialog_selection;
        dialog_selection = 
                JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user? (This cannot be undone)", "Delete User", JOptionPane. YES_NO_OPTION);
        
        if(0 == dialog_selection)
        {
            String employee_id = (String)user_jtable.getValueAt(current_selected_row, EMPLOYEE_ID_COLUMN);
            employee_handler.deleteEmployee(employee_id);
            clearUserFormData();
            deleteSelectedRow();
        }
        
        
    }//GEN-LAST:event_delete_user_jbuttonActionPerformed

    private void search_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_jbuttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) user_jtable.getModel();
        //First clear all rows
        model.setRowCount(0);
        
        ArrayList<Employee> found_employees = new ArrayList<>();
        
        if(first_name_jradiobutton.isSelected())
        {
            found_employees = employee_handler.searchEmployees("first_name", search_first_name_jtextfield.getText());
        }
        else if(last_name_jradiobutton.isSelected())
        {
            found_employees = employee_handler.searchEmployees("last_name", search_last_name_jtextfield.getText());
        }
        else if(employee_id_jradiobutton.isSelected())
        {
            found_employees = employee_handler.searchEmployees("employee_id", search_employee_id_jtextfield.getText());
        }
        
        for (Employee employee : found_employees)
        {
            createEmployeeRow(employee);
        }
        
    }//GEN-LAST:event_search_jbuttonActionPerformed

    private void menu_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jbuttonActionPerformed
        CardLayout card = (CardLayout)this.getParent().getLayout();
        card.show(this.getParent(), "launcherMenuPanel");
    }//GEN-LAST:event_menu_jbuttonActionPerformed

    private void user_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_jtableMouseClicked
        int new_selected_row = user_jtable.getSelectedRow();
        
        //If a the user selected a different row
        if(new_selected_row != current_selected_row) {
            
            current_selected_row = new_selected_row;
            String employee_id = (String)user_jtable.getValueAt(current_selected_row, EMPLOYEE_ID_COLUMN);

            if(employee_id != null)
            {
                //Set the form data based on selected employee
                setEmployeeFormData(employee_id);
                
                modify_user_jbutton.setEnabled(true);
                delete_user_jbutton.setEnabled(true);
            }
            else
            {
                modify_user_jbutton.setEnabled(false);
                delete_user_jbutton.setEnabled(false);
            }
            
            disableUserFormData();
            //Make sure that the standard buttons are shown
            CardLayout card = (CardLayout)user_dynamic_button_panel.getLayout();
            card.show(user_dynamic_button_panel, "userStandardButtonsPanel");
        }
    }//GEN-LAST:event_user_jtableMouseClicked

    private void modify_user_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_user_jbuttonActionPerformed
        enableUserFormData();
        
        //Change the buttons to the new options for modifying a user
        CardLayout card = (CardLayout)user_dynamic_button_panel.getLayout();
        card.show(user_dynamic_button_panel, "userModifyButtonsPanel");
        
    }//GEN-LAST:event_modify_user_jbuttonActionPerformed

    private void submit_add_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_add_user_buttonActionPerformed
        if(isInputDataValid())
        {
            Employee new_employee = new Employee();
            new_employee.setEmployeeId(employee_id_textfield.getText());
            new_employee.setFirstName(first_name_textfield.getText());
            new_employee.setLastName(last_name_textfield.getText());
            new_employee.setAddress(address_textfield.getText());
            new_employee.setSsn(Integer.parseInt(ssn_textfield.getText()));
            new_employee.setWage(Double.parseDouble(wage_textfield.getText()));
            new_employee.setHours(Double.parseDouble(hours_textfield.getText()));
            new_employee.setAccountPassword(password_textfield.getText());
            new_employee.setIsAdmin(admin_checkbox.isSelected());

            //Create in database
            employee_handler.addEmployee(new_employee);
            
            //Add row to table
            createEmployeeRow(new_employee);
            
            //Change back to the standard buttons
            CardLayout card = (CardLayout)user_dynamic_button_panel.getLayout();
            card.show(user_dynamic_button_panel, "userStandardButtonsPanel");
        
            disableUserFormData();
        }
    }//GEN-LAST:event_submit_add_user_buttonActionPerformed

    private boolean isInputDataValid()
    {
        if(employee_id_textfield.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID entered", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try {
            Integer.parseInt(ssn_textfield.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid SSN entered", "ERROR", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        
        try {
            Double.parseDouble(wage_textfield.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Wage entered", "ERROR", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        
        try {
            Double.parseDouble(hours_textfield.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Hours entered", "ERROR", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        
        return true;
    }
    
    private void cancel_add_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_add_user_buttonActionPerformed
        //Change back to the standard buttons
        CardLayout card = (CardLayout)user_dynamic_button_panel.getLayout();
        card.show(user_dynamic_button_panel, "userStandardButtonsPanel");
        
        clearUserFormData();
        disableUserFormData();
    }//GEN-LAST:event_cancel_add_user_buttonActionPerformed

    private void submit_modify_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_modify_user_buttonActionPerformed
        if(isInputDataValid())
        {
            Employee modified_employee = new Employee();
            modified_employee.setEmployeeId(employee_id_textfield.getText());
            modified_employee.setFirstName(first_name_textfield.getText());
            modified_employee.setLastName(last_name_textfield.getText());
            modified_employee.setAddress(address_textfield.getText());
            modified_employee.setSsn(Integer.parseInt(ssn_textfield.getText()));
            modified_employee.setWage(Double.parseDouble(wage_textfield.getText()));
            modified_employee.setHours(Double.parseDouble(hours_textfield.getText()));
            modified_employee.setAccountPassword(password_textfield.getText());
            modified_employee.setIsAdmin(admin_checkbox.isSelected());

            //Modify in database
            employee_handler.updateEmployee(modified_employee);
            
            modifyEmployeeRow(modified_employee);
            
            //Change back to the standard buttons
            CardLayout card = (CardLayout)user_dynamic_button_panel.getLayout();
            card.show(user_dynamic_button_panel, "userStandardButtonsPanel");
        
            disableUserFormData();
        }
    }//GEN-LAST:event_submit_modify_user_buttonActionPerformed

    private void cancel_modify_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_modify_user_buttonActionPerformed
        String employee_id = (String)user_jtable.getValueAt(current_selected_row, EMPLOYEE_ID_COLUMN);
        //Set back to original data
        setEmployeeFormData(employee_id);
        
        disableUserFormData();

        //Change back to the standard buttons
        CardLayout card = (CardLayout)user_dynamic_button_panel.getLayout();
        card.show(user_dynamic_button_panel, "userStandardButtonsPanel");
    }//GEN-LAST:event_cancel_modify_user_buttonActionPerformed

    private void setEmployeeFormData(String employee_id)
    {
        Employee employee_to_set = employee_handler.getEmployee(employee_id);
        employee_id_textfield.setText(employee_to_set.getEmployeeId());
        first_name_textfield.setText(employee_to_set.getFirstName());
        last_name_textfield.setText(employee_to_set.getLastName());
        address_textfield.setText(employee_to_set.getAddress());
        ssn_textfield.setText("" + employee_to_set.getSsn());
        wage_textfield.setText("" + employee_to_set.getWage());
        hours_textfield.setText("" + employee_to_set.getHours());
        password_textfield.setText(employee_to_set.getAccountPassword());
        admin_checkbox.setSelected(employee_to_set.getIsAdmin());
    }
    
    private void clearUserFormData() {
        employee_id_textfield.setText(null);
        first_name_textfield.setText(null);
        last_name_textfield.setText(null);
        address_textfield.setText(null);
        ssn_textfield.setText(null);
        wage_textfield.setText(null);
        hours_textfield.setText(null);
        password_textfield.setText(null);
        admin_checkbox.setSelected(false);
    }
    
    private void enableUserFormData()
    {
        first_name_textfield.setEditable(true);
        last_name_textfield.setEditable(true);
        address_textfield.setEditable(true);
        ssn_textfield.setEditable(true);
        wage_textfield.setEditable(true);
        hours_textfield.setEditable(true);
        password_textfield.setEditable(true);
        admin_checkbox.setEnabled(true);
    }
    
    private void disableUserFormData()
    {
        employee_id_textfield.setEditable(false);
        first_name_textfield.setEditable(false);
        last_name_textfield.setEditable(false);
        address_textfield.setEditable(false);
        ssn_textfield.setEditable(false);
        wage_textfield.setEditable(false);
        hours_textfield.setEditable(false);
        password_textfield.setEditable(false);
        admin_checkbox.setEnabled(false);
    }
    
    private void deleteSelectedRow() {
        DefaultTableModel model = (DefaultTableModel) user_jtable.getModel();
        model.removeRow(current_selected_row);
    }
    
    private void showAllEmployees() {
        ArrayList<Employee> employee_list = employee_handler.getAllEmployees();
        
        for (Employee employee : employee_list)
        {
            createEmployeeRow(employee);
        }
    }
    
    private void createEmployeeRow(Employee employee) {
        DefaultTableModel model = (DefaultTableModel) user_jtable.getModel();    
        
        Object[] row =
            {
                employee.getEmployeeId(),
                employee.getFirstName(),
                employee.getLastName(),
                employee.getAddress(),
                employee.getWage(),
                employee.getHours()
            };
        model.addRow(row);
    }
    
    private void modifyEmployeeRow(Employee employee) {
        user_jtable.setValueAt(employee.getEmployeeId(), current_selected_row, EMPLOYEE_ID_COLUMN);
        user_jtable.setValueAt(employee.getFirstName(), current_selected_row, EMPLOYEE_FIRST_NAME_COLUMN);
        user_jtable.setValueAt(employee.getLastName(), current_selected_row, EMPLOYEE_LAST_NAME_COLUMN);
        user_jtable.setValueAt(employee.getAddress(), current_selected_row, EMPLOYEE_ADDRESS_COLUMN);
        user_jtable.setValueAt(employee.getWage(), current_selected_row, EMPLOYEE_WAGE_COLUMN);
        user_jtable.setValueAt(employee.getHours(), current_selected_row, EMPLOYEE_HOURS_COLUMN);
    }

    private final int EMPLOYEE_ID_COLUMN;
    private final int EMPLOYEE_FIRST_NAME_COLUMN;
    private final int EMPLOYEE_LAST_NAME_COLUMN;
    private final int EMPLOYEE_ADDRESS_COLUMN;
    private final int EMPLOYEE_WAGE_COLUMN;
    private final int EMPLOYEE_HOURS_COLUMN;
    private int current_selected_row;
    Employee_I employee_handler;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_user_jbutton;
    private javax.swing.JLabel address_jlabel;
    private javax.swing.JTextField address_textfield;
    private javax.swing.JCheckBox admin_checkbox;
    private javax.swing.JPanel button_panel;
    private javax.swing.JButton cancel_add_user_button;
    private javax.swing.JButton cancel_modify_user_button;
    private javax.swing.JLabel company_name_label;
    private javax.swing.JButton delete_user_jbutton;
    private javax.swing.JLabel employee_id_jlabel;
    private javax.swing.JRadioButton employee_id_jradiobutton;
    private javax.swing.JTextField employee_id_textfield;
    private javax.swing.JLabel first_name_jlabel;
    private javax.swing.JRadioButton first_name_jradiobutton;
    private javax.swing.JTextField first_name_textfield;
    private javax.swing.JLabel hours_jlabel;
    private javax.swing.JTextField hours_textfield;
    private javax.swing.JLabel icon_jLabel;
    private javax.swing.JPanel icon_jpanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel last_name_jlabel;
    private javax.swing.JRadioButton last_name_jradiobutton;
    private javax.swing.JTextField last_name_textfield;
    private javax.swing.JPanel loco_icon_panel;
    private javax.swing.JLabel logo_jlabel;
    private javax.swing.JPanel logo_jpanel;
    private javax.swing.JButton menu_jbutton;
    private javax.swing.JButton modify_user_jbutton;
    private javax.swing.JTabbedPane option_jtabbedpane;
    private javax.swing.JLabel password_jlabel;
    private javax.swing.JTextField password_textfield;
    private javax.swing.JTextField search_employee_id_jtextfield;
    private javax.swing.JTextField search_first_name_jtextfield;
    private javax.swing.JButton search_jbutton;
    private javax.swing.JPanel search_jpanel;
    private javax.swing.JTextField search_last_name_jtextfield;
    private javax.swing.ButtonGroup search_radio_button_group;
    private javax.swing.JLabel ssn_jlabel;
    private javax.swing.JTextField ssn_textfield;
    private javax.swing.JButton submit_add_user_button;
    private javax.swing.JButton submit_modify_user_button;
    private javax.swing.JPanel user_add_buttons;
    private javax.swing.JPanel user_dynamic_button_panel;
    private javax.swing.JPanel user_jpanel;
    private javax.swing.JTable user_jtable;
    private javax.swing.JPanel user_modify_buttons;
    private javax.swing.JPanel user_standard_buttons;
    private javax.swing.JPanel user_table_jpanel;
    private javax.swing.JLabel wage_jlabel;
    private javax.swing.JTextField wage_textfield;
    // End of variables declaration//GEN-END:variables
}
