/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.gui.core;

import java.awt.CardLayout;

/**
 *
 * @author Dakota
 */
public class UserManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserManagementPanel
     */
    public UserManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_jpanel = new javax.swing.JPanel();
        loco_icon_panel = new javax.swing.JPanel();
        logo_jlabel = new javax.swing.JLabel();
        company_name_label = new javax.swing.JLabel();
        option_jtabbedpane = new javax.swing.JTabbedPane();
        user_jpanel = new javax.swing.JPanel();
        icon_jpanel = new javax.swing.JPanel();
        icon_jLabel = new javax.swing.JLabel();
        employee_id_jlabel = new javax.swing.JLabel();
        first_name_jlabel = new javax.swing.JLabel();
        employee_id_textfield = new javax.swing.JTextField();
        first_name_textfield = new javax.swing.JTextField();
        address_jlabel = new javax.swing.JLabel();
        address_textfield = new javax.swing.JTextField();
        ssn_jlabel = new javax.swing.JLabel();
        ssn_textfield = new javax.swing.JTextField();
        wage_jlabel = new javax.swing.JLabel();
        wage_textfield = new javax.swing.JTextField();
        last_name_jlabel = new javax.swing.JLabel();
        last_name_textfield = new javax.swing.JTextField();
        add_user_jbutton = new javax.swing.JButton();
        delete_user_jbutton = new javax.swing.JButton();
        modify_user_jbutton = new javax.swing.JButton();
        hours_jlabel = new javax.swing.JLabel();
        hours_textfield = new javax.swing.JTextField();
        password_jlabel = new javax.swing.JLabel();
        password_textfield = new javax.swing.JTextField();
        admin_checkbox = new javax.swing.JCheckBox();
        search_jpanel = new javax.swing.JPanel();
        first_name_jradiobutton = new javax.swing.JRadioButton();
        last_name_jradiobutton = new javax.swing.JRadioButton();
        employee_id_jradiobutton = new javax.swing.JRadioButton();
        search_first_name_jtextfield = new javax.swing.JTextField();
        search_last_name_jtextfield = new javax.swing.JTextField();
        search_employee_id_jtextfield = new javax.swing.JTextField();
        search_jbutton = new javax.swing.JButton();
        button_panel = new javax.swing.JPanel();
        menu_jbutton = new javax.swing.JButton();
        product_table_jpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1878, 1038));

        logo_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        loco_icon_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logo_jlabel.setText("LOGO");

        javax.swing.GroupLayout loco_icon_panelLayout = new javax.swing.GroupLayout(loco_icon_panel);
        loco_icon_panel.setLayout(loco_icon_panelLayout);
        loco_icon_panelLayout.setHorizontalGroup(
            loco_icon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loco_icon_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo_jlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loco_icon_panelLayout.setVerticalGroup(
            loco_icon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loco_icon_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logo_jlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        company_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        company_name_label.setText("COMPANY NAME");

        javax.swing.GroupLayout logo_jpanelLayout = new javax.swing.GroupLayout(logo_jpanel);
        logo_jpanel.setLayout(logo_jpanelLayout);
        logo_jpanelLayout.setHorizontalGroup(
            logo_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_jpanelLayout.createSequentialGroup()
                .addComponent(loco_icon_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logo_jpanelLayout.setVerticalGroup(
            logo_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo_jpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loco_icon_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(logo_jpanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(company_name_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        user_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        icon_jpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        icon_jLabel.setText("ICON");

        javax.swing.GroupLayout icon_jpanelLayout = new javax.swing.GroupLayout(icon_jpanel);
        icon_jpanel.setLayout(icon_jpanelLayout);
        icon_jpanelLayout.setHorizontalGroup(
            icon_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, icon_jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_jLabel)
                .addGap(32, 32, 32))
        );
        icon_jpanelLayout.setVerticalGroup(
            icon_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(icon_jpanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(icon_jLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employee_id_jlabel.setText("Employee ID :");

        first_name_jlabel.setText("First Name : ");

        first_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_name_textfieldActionPerformed(evt);
            }
        });

        address_jlabel.setText("Address :");

        ssn_jlabel.setText("SSN :");

        ssn_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssn_textfieldActionPerformed(evt);
            }
        });

        wage_jlabel.setText("Wage :");

        wage_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wage_textfieldActionPerformed(evt);
            }
        });

        last_name_jlabel.setText("Last Name :");

        add_user_jbutton.setText("Add User");
        add_user_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_jbuttonActionPerformed(evt);
            }
        });

        delete_user_jbutton.setText("Delete User");
        delete_user_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_user_jbuttonActionPerformed(evt);
            }
        });

        modify_user_jbutton.setText("Modify User");

        hours_jlabel.setText("Hours :");

        password_jlabel.setText("Password");

        admin_checkbox.setText("Administrator");

        javax.swing.GroupLayout user_jpanelLayout = new javax.swing.GroupLayout(user_jpanel);
        user_jpanel.setLayout(user_jpanelLayout);
        user_jpanelLayout.setHorizontalGroup(
            user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address_jlabel)
                    .addComponent(last_name_jlabel)
                    .addComponent(ssn_jlabel)
                    .addComponent(wage_jlabel)
                    .addComponent(hours_jlabel)
                    .addComponent(password_jlabel)
                    .addComponent(first_name_jlabel)
                    .addComponent(employee_id_jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(last_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssn_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wage_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_jpanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(icon_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(user_jpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(admin_checkbox)
                    .addGroup(user_jpanelLayout.createSequentialGroup()
                        .addComponent(add_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modify_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(delete_user_jbutton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        user_jpanelLayout.setVerticalGroup(
            user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_jpanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee_id_jlabel)
                    .addComponent(employee_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name_jlabel))
                .addGap(18, 18, 18)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_name_jlabel)
                    .addComponent(last_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_jlabel))
                .addGap(15, 15, 15)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssn_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssn_jlabel))
                .addGap(18, 18, 18)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wage_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wage_jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hours_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours_jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_jlabel)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(admin_checkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(user_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_user_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        option_jtabbedpane.addTab("User", null, user_jpanel, "");

        first_name_jradiobutton.setText("First Name :");
        first_name_jradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_name_jradiobuttonActionPerformed(evt);
            }
        });

        last_name_jradiobutton.setText("Last Name :");
        last_name_jradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_name_jradiobuttonActionPerformed(evt);
            }
        });

        employee_id_jradiobutton.setText("Employee ID :");
        employee_id_jradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_id_jradiobuttonActionPerformed(evt);
            }
        });

        search_last_name_jtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_last_name_jtextfieldActionPerformed(evt);
            }
        });

        search_employee_id_jtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_employee_id_jtextfieldActionPerformed(evt);
            }
        });

        search_jbutton.setText("Search");
        search_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_jpanelLayout = new javax.swing.GroupLayout(search_jpanel);
        search_jpanel.setLayout(search_jpanelLayout);
        search_jpanelLayout.setHorizontalGroup(
            search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_jpanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_jpanelLayout.createSequentialGroup()
                        .addComponent(first_name_jradiobutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(search_first_name_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(search_jpanelLayout.createSequentialGroup()
                        .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(last_name_jradiobutton)
                            .addComponent(employee_id_jradiobutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search_employee_id_jtextfield)
                            .addComponent(search_last_name_jtextfield))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(search_jpanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(search_jbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        search_jpanelLayout.setVerticalGroup(
            search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_jpanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name_jradiobutton)
                    .addComponent(search_first_name_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_name_jradiobutton)
                    .addComponent(search_last_name_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(search_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_employee_id_jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee_id_jradiobutton))
                .addGap(39, 39, 39)
                .addComponent(search_jbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        option_jtabbedpane.addTab("Search", null, search_jpanel, "");

        button_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menu_jbutton.setText("Menu");
        menu_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_panelLayout = new javax.swing.GroupLayout(button_panel);
        button_panel.setLayout(button_panelLayout);
        button_panelLayout.setHorizontalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(menu_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_panelLayout.setVerticalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        product_table_jpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout product_table_jpanelLayout = new javax.swing.GroupLayout(product_table_jpanel);
        product_table_jpanel.setLayout(product_table_jpanelLayout);
        product_table_jpanelLayout.setHorizontalGroup(
            product_table_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_table_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        product_table_jpanelLayout.setVerticalGroup(
            product_table_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_table_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(option_jtabbedpane)
                    .addComponent(button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product_table_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(option_jtabbedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(product_table_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void first_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_name_textfieldActionPerformed

    private void ssn_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssn_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssn_textfieldActionPerformed

    private void wage_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wage_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wage_textfieldActionPerformed

    private void add_user_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_jbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_user_jbuttonActionPerformed

    private void delete_user_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_user_jbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_user_jbuttonActionPerformed

    private void first_name_jradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_name_jradiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_name_jradiobuttonActionPerformed

    private void last_name_jradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_name_jradiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_name_jradiobuttonActionPerformed

    private void employee_id_jradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_id_jradiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employee_id_jradiobuttonActionPerformed

    private void search_last_name_jtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_last_name_jtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_last_name_jtextfieldActionPerformed

    private void search_employee_id_jtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_employee_id_jtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_employee_id_jtextfieldActionPerformed

    private void search_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_jbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_jbuttonActionPerformed

    private void menu_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jbuttonActionPerformed
        CardLayout card = (CardLayout)this.getParent().getLayout();
        card.show(this.getParent(), "launcherMenuPanel");
    }//GEN-LAST:event_menu_jbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_user_jbutton;
    private javax.swing.JLabel address_jlabel;
    private javax.swing.JTextField address_textfield;
    private javax.swing.JCheckBox admin_checkbox;
    private javax.swing.JPanel button_panel;
    private javax.swing.JLabel company_name_label;
    private javax.swing.JButton delete_user_jbutton;
    private javax.swing.JLabel employee_id_jlabel;
    private javax.swing.JRadioButton employee_id_jradiobutton;
    private javax.swing.JTextField employee_id_textfield;
    private javax.swing.JLabel first_name_jlabel;
    private javax.swing.JRadioButton first_name_jradiobutton;
    private javax.swing.JTextField first_name_textfield;
    private javax.swing.JLabel hours_jlabel;
    private javax.swing.JTextField hours_textfield;
    private javax.swing.JLabel icon_jLabel;
    private javax.swing.JPanel icon_jpanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel last_name_jlabel;
    private javax.swing.JRadioButton last_name_jradiobutton;
    private javax.swing.JTextField last_name_textfield;
    private javax.swing.JPanel loco_icon_panel;
    private javax.swing.JLabel logo_jlabel;
    private javax.swing.JPanel logo_jpanel;
    private javax.swing.JButton menu_jbutton;
    private javax.swing.JButton modify_user_jbutton;
    private javax.swing.JTabbedPane option_jtabbedpane;
    private javax.swing.JLabel password_jlabel;
    private javax.swing.JTextField password_textfield;
    private javax.swing.JPanel product_table_jpanel;
    private javax.swing.JTextField search_employee_id_jtextfield;
    private javax.swing.JTextField search_first_name_jtextfield;
    private javax.swing.JButton search_jbutton;
    private javax.swing.JPanel search_jpanel;
    private javax.swing.JTextField search_last_name_jtextfield;
    private javax.swing.JLabel ssn_jlabel;
    private javax.swing.JTextField ssn_textfield;
    private javax.swing.JPanel user_jpanel;
    private javax.swing.JLabel wage_jlabel;
    private javax.swing.JTextField wage_textfield;
    // End of variables declaration//GEN-END:variables
}
